[changelog]
commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^removed", group = "removed" },
    { message = "^fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = "^docs", group = "documentation" },
    { message = "^refactor", skip = true },
    { message = "^test", skip = true },
    { message = "^chore", skip = true },
    { message = "^.*", group = "other" },
]
